export const cards1 = [
  {
    somekey: "card-1",
    imageUrl: "./assets/gym_equip.jpeg",
    height: "h-120",
    width: "w-190",
    imageHeight: "h-150",
    title: "Premium Gym Equipment",
    description:
      "Our gym features premium, state-of-the-art equipment designed to cater to every fitness enthusiast's needs. From advanced cardio machines to strength training apparatus, each piece of equipment is crafted to provide optimal performance, safety, and comfort. Whether you are a beginner or an experienced athlete, our high-quality machines ensure an effective and enjoyable workout experience.",
    parallaxSpeed: 3,
    direction: "y" as const,
    zIndex: 50,
    enableRotation: false,
    rotationIntensity: 1,
    enableScale: false,
    scaleStart: 0.7,
    scaleEnd: 1,
    position: "relative" as const,
    top: "20px",
    left: "-100px",
  },
  {
    somekey: "card-2",
    imageUrl: "./assets/personel_train.jpeg",
    height: "h-102",
    width: "w-160",
    imageHeight: "h-80",
    title: "Personal Training",
    description:
      "Our certified personal trainers provide tailored workout plans to help you achieve your fitness goals efficiently and safely. Each session is customized to your experience level, physical condition, and objectives, ensuring maximum results and motivation. With expert guidance, you can improve your technique, stay accountable, and unlock your full potential in a supportive environment.",
    parallaxSpeed: 0.8,
    direction: "y" as const,
    zIndex: 45,
    enableRotation: false,
    rotationIntensity: 0,
    enableScale: false,
    scaleStart: 0.9,
    scaleEnd: 1.0,
    position: "relative" as const,
    top: "100px",
    left: "50px",
  },
  {
    somekey: "card-3",
    imageUrl: "./assets/grp_class.jpeg",
    height: "h-84",
    width: "w-104",
    imageHeight: "h-70",
    title: "Group Classes",
    description:
      "Join our dynamic group classes to experience the energy and motivation of working out with others. From high-intensity training sessions to calming yoga classes, our diverse offerings cater to all fitness levels. Engaging in group activities not only helps improve physical fitness but also fosters social connections and a sense of community, making your fitness journey enjoyable and rewarding.",
    parallaxSpeed: 0.7,
    direction: "y" as const,
    zIndex: 52,
    enableRotation: true,
    rotationIntensity: 3,
    enableScale: false,
    scaleStart: 0.8,
    scaleEnd: 1.2,
    position: "relative" as const,
    left: "10px",
  },
  {
    somekey: "card-4",
    imageUrl: "./assets/mma.jpeg",
    height: "h-114",
    width: "w-180",
    imageHeight: "h-110",
    title: "Nutrition Plans",
    description:
      "Our nutrition plans are designed to complement your fitness routine and help you achieve your health goals effectively. We provide personalized meal strategies based on your dietary needs, preferences, and fitness objectives. By combining proper nutrition with your workouts, you can enhance performance, boost energy levels, and see sustainable results while maintaining a balanced and healthy lifestyle.",
    parallaxSpeed: 3,
    direction: "y" as const,
    zIndex: 48,
    enableRotation: false,
    rotationIntensity: 5,
    enableScale: true,
    scaleStart: 1,
    scaleEnd: 1.1,
    position: "relative" as const,
    right: "15px",
  },
];
