export const cards1 = [
  {
    somekey: "card-1",
    imageUrl: "./assets/gym1.jpg",
    height: "h-120",
    width: "w-190",
    imageHeight: "h-150",
    title: "Premium Gym Equipment",
    description: "State-of-the-art machines for your workout routine",
    parallaxSpeed: 3,
    direction: "y" as const,
    zIndex: 50,
    enableRotation: false,
    rotationIntensity: 1,
    enableScale: false,
    scaleStart: 0.7,
    scaleEnd: 1,
    position: "relative" as const,
    top: "20px",
    left: "-100px",
  },
  {
    somekey: "card-2",
    imageUrl: "./assets/gym2.jpg",
    height: "h-102",
    width: "w-160",
    imageHeight: "h-80",
    title: "Personal Training",
    description: "Certified trainers for customized workout plans",
    parallaxSpeed: 0.8,
    direction: "y" as const,
    zIndex: 45,
    enableRotation: false,
    rotationIntensity: 0,
    enableScale: false,
    scaleStart: 0.9,
    scaleEnd: 1.0,
    position: "relative" as const,
    top: "100px",
    left: "50px",
  },
  {
    somekey: "card-3",
    imageUrl: "./assets/gym3.jpg",
    height: "h-64",
    width: "w-80",
    imageHeight: "h-70",
    title: "Group Classes",
    description: "Join our energizing group fitness sessions",
    parallaxSpeed: 0.7,
    direction: "y" as const,
    zIndex: 52,
    enableRotation: true,
    rotationIntensity: 3,
    enableScale: false,
    scaleStart: 0.8,
    scaleEnd: 1.2,
    position: "relative" as const,
    left: "10px",
  },
  {
    somekey: "card-4",
    imageUrl: "./assets/gym1.jpg",
    height: "h-114",
    width: "w-180",
    imageHeight: "h-110",
    title: "Nutrition Plans",
    description: "Customized meal plans for your fitness goals",
    parallaxSpeed: 3,
    direction: "y" as const,
    zIndex: 48,
    enableRotation: false,
    rotationIntensity: 5,
    enableScale: true,
    scaleStart: 1,
    scaleEnd: 1.1,
    position: "relative" as const,
    right: "15px",
  },
];
